development:
  stage: deploy
  environment: production
  script:
  - mkdir ~/.aws/
  - cd ~/.aws/credentials
  - echo "[eb-cli]\naws_access_key_id = %s\naws_secret_access_key = %s\n" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
  - cd ~/.aws/config
  - echo "[profile eb-cli]\nregion=ap-southeast-1\noutput=json" >> ~/.aws/config
  - eb deploy Php-EB-env
  only:
  - master
