branch-defaults:
  master:
    environment: funwitheb-production
global:
  application_name: funwitheb
  default_ec2_keyname: funwitheb-ci
  default_platform: 64bit Amazon Linux 2016.03 v2.1.5 running PHP 7.0
  default_region: us-east-1
  profile: eb-cli
  sc: git
