branch-defaults:
  master:
    environment: Php-EB-env
global:
  application_name: phpEB
  default_ec2_keyname: phpEB-ci
  default_platform: 64bit Amazon Linux 2016.03 v3.5.7 running PHP 8.1
  default_region: us-east-1
  profile: eb-cli
  sc: git
